### ISSUE TITLE
dynamically change color for each ecosystem

### ISSUE THREAD

**Issue by 0xpentacle** [pentacledotai/pentacle#17]
Allow devs to pass in the 3 color variables for each chart - marked in bold

ETH 
d3.**scaleOrdinal**(d3.**quantize**(d3.**interpolateRainbow**, data.children.length + 1))

SOL
d3.**scaleOrdinal**(d3.**quantize**(d3.**interpolateCool**, data.children.length + 1))

**Comment by 0xpentacle** [comment]
can't decide if bug or enhancement!
prob regression :)

**Comment by mchl18** [comment]
regression and enhancement!
#20
